<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students [
<!ELEMENT students (student+)>
<!ELEMENT student (name, age, course, address?, phone, dob)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT course (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT dob (#PCDATA)>
<!ATTLIST student id CDATA #REQUIRED>
<!-- Here we can give #IMPLIED => optional, (#FIXED value), or (default value) values if needed -->
<!-- here c => single,c+ => one or more ,c? => zero or one,c* => zero or more-->
]>
<students>
    <student id="1">
        <name>Sakthi</name>
        <age>20</age>
        <course>IT</course>
        <address>Madurai</address>
        <phone>9751423916</phone>
        <dob>23-11-2004</dob>
    </student>
    <student id="2">
        <name>Roshini</name>
        <age>19</age>
        <course>ECE</course>
        <phone>9940467525</phone>
        <dob>08-09-2005</dob>
    </student>
    <student id="3">
        <name>Harshi</name>
        <age>19</age>
        <course>CSE</course>
        <address>Coimbatore</address>
        <phone>9444901665</phone>
        <dob>01-12-2005</dob>
    </student>
</students>